domain: apps.xxx.openshift.com

postgres:
  host: postgres
  name: postgres
  user: postgres
  password: postgres
  port: "5432"

oidc:
  issuer: ''
  secret: ''

bucket:
  name: rhtpa
  region: 'http://minio.minio.svc.cluster.local:9000'
  user: minio
  password: ''

