domain: apps.rmohbjxeoac4904b59.westus.aroapp.io
authelia_host_name: authelia
devhub_host_name: backstage-rhdh-rhdh
tpa_host_name: server-tpa

authentication_backend:
  ldap:
    implementation: glauth
    address: "ldap://glauth"
    base_dn: "dc=latam,dc=redhat"
    user: "cn=redhat,cn=ssa,dc=latam,dc=redhat"
    password: redhat
    users_filter: (&({username_attribute}={input})(objectClass=posixAccount))
    groups_filter: (&(uniqueMember={dn})(objectClass=posixGroup))

clients:
  developer_hub:
    client_secret: $pbkdf2-sha512$310000$dnM5jLQcosHJWJDIitGB5A$Phb4GuHZZUVIK6BHxlkkHmW57GFiuQdHjYyJzH/cpUlWquYTPS3wgFkhfmgje2fkenr5KQVbWwc0EgwpBot97A # BrxaCt70att-zRlXsGMMJh5KFAW3GxkL6ABzUQS6Y7S_glJGsQpZsFDMVoDZrSrxsTNhdkto
    redirect_uris:
      - https://{{ .Values.devhub_host_name }}.{{ .Values.domain }}/api/auth/oidc/handler/frame

  trusted_profile_analyser:
    client_secret: $pbkdf2-sha512$310000$dnM5jLQcosHJWJDIitGB5A$Phb4GuHZZUVIK6BHxlkkHmW57GFiuQdHjYyJzH/cpUlWquYTPS3wgFkhfmgje2fkenr5KQVbWwc0EgwpBot97A # BrxaCt70att-zRlXsGMMJh5KFAW3GxkL6ABzUQS6Y7S_glJGsQpZsFDMVoDZrSrxsTNhdkto
    redirect_uris:
      - 'https://{{ .Values.tpa_host_name }}.{{ .Values.domain }}'
      - 'https://{{ .Values.tpa_host_name }}.{{ .Values.domain }}/*'

  trusted_artifact_signer:
    client_secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'  # The digest of 'insecure_secret'.

route:
  to:
    kind: Service
    name: authelia
  port:
    targetPort: nginx
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

nginx_sub_filter:
  end_session_endpoint: https://{{ .Values.authelia_host_name }}.{{ .Values.domain }}/logout?rd=https://{{ .Values.tpa_host_name }}.{{ .Values.domain }}