apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      enableServiceLinks: false
      {{- if .Values.init_secrets }}
      initContainers:
      - name: create-secrets
        image: quay.io/zcve/authelia
        env:
        - name: NS
          value: {{ .Release.Namespace }}
        command: ["bash", "-c"]
        args:
        - |-
          kubectl get secrets -n {{ .Release.Namespace }} authelia-secrets-generated > /dev/null 2>&1 || \
          export AUTH_DEVHUB=`uuidgen` && \
          export AUTH_RHTPACLI=`uuidgen` && \
          export AUTH_TAS=`uuidgen` && \
          authelia crypto pair rsa generate -d /tmp && \
          kubectl -n $NS apply -f - <<EOF
          apiVersion: v1
          kind: Secret
          metadata:
            name: authelia-secrets
            labels:
              {{- include "helm.labels" . | nindent 14 }}
            annotations:
              "helm.sh/resource-policy": keep              
          type: Opaque
          stringData:
            ldap_passwd: {{ .Values.ldap_passwd }}
            session: "$(authelia crypto rand | cut -c 15-)"
            storage: "$(authelia crypto rand | cut -c 15-)"
            devhub: "$(authelia crypto hash generate pbkdf2 --variant sha512 --password $AUTH_DEVHUB  | cut -c 9-)"
            rhtpacli: "$(authelia crypto hash generate pbkdf2 --variant sha512 --password $AUTH_RHTPACLI  | cut -c 9-)"
            tas: "$(authelia crypto hash generate pbkdf2 --variant sha512 --password $AUTH_TAS  | cut -c 9-)"
            jwkskey: |-
          $(sed -e 's/^/    /g' /tmp/private.pem)
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: authelia-secrets-generated
            labels:
              {{- include "helm.labels" . | nindent 4 }}            
          type: Opaque
          stringData:        
            devhub: "$AUTH_DEVHUB"
            rhtpacli: "$AUTH_RHTPACLI"
            tas: "$AUTH_TAS"
          EOF
      {{- end }}
      containers:
        - name: authelia
          image: ghcr.io/authelia/authelia
          env:
          - name: X_AUTHELIA_CONFIG_FILTERS
            value: template
          ports:
            - containerPort: 9091
          volumeMounts:
            - name: authelia-config-volume
              mountPath: /config
            - name: config-secrets
              mountPath: /secrets
              readOnly: true
        - name: nginx
          image: registry.access.redhat.com/hi/nginx
          ports:
            - containerPort: 9081       
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d             
      volumes:
        - name: authelia-config-volume
          configMap:
            name: authelia-config
        - name: nginx-config-volume
          configMap:
            name: nginx-config       
        - name: config-secrets
          secret:
            secretName: authelia-secrets

