{{- if .Values.route }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: authelia-default
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.authelia_host_name }}.{{ .Values.domain }}
  {{- .Values.route.default | toYaml | nindent 2 }}
{{- end }}
---
{{- if .Values.route }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: authelia-tpa
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.tpa_auth_host_name }}.{{ .Values.domain }}
  {{- .Values.route.tpa | toYaml | nindent 2 }}
{{- end }}
