apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}   
type: Opaque
stringData:
  ldap_passwd: {{ .Values.ldap_passwd }}
  session: {{ regexReplaceAll "Random Value: (.*)" .Values.session.secret "$1" }}
  storage: {{ regexReplaceAll "Random Value: (.*)" .Values.storage.secret "$1" }}
  devhub: {{ regexReplaceAll "Digest: (.*)" .Values.clients.developer_hub.client_secret "$1" }}
  rhtpacli: {{ regexReplaceAll "Digest: (.*)"  .Values.clients.trusted_profile_analyser.client_secret "$1" }}
  tas: {{ regexReplaceAll "Digest: (.*)" .Values.clients.trusted_artifact_signer.client_secret "$1" }}
  jwkskey: |-
    {{- .Values.idp.jwks.pkfile | nindent 4 }}
