apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: {{ .Release.Namespace }}
  labels:
    app: authelia
spec:
  selector:
    app: authelia
  ports:
    - name: authelia
      protocol: TCP
      port: 9091
      targetPort: 9091
    - name: nginx 
      protocol: TCP
      port: 9081
      targetPort: 9081      
  type: ClusterIP #
