apiVersion: batch/v1
kind: Job
metadata:
  name: remove-csv
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: check-devspaces-operator
          image: quay.io/zcve/bashkc
          command:
            - bash
            - -c    
            - |
              csv=`kubectl get subscription kubernetes-imagepuller-operator -n openshift-operators -o jsonpath='{$.status.installedCSV}'`
              kubectl delete subscription kubernetes-imagepuller-operator -n openshift-operators
              kubectl delete csv $csv