apiVersion: che.eclipse.org/v1alpha1
kind: KubernetesImagePuller
metadata:
  name: devspaces-image-puller
  namespace: {{ .Release.Namespace }}
spec:
  configMapName: k8s-image-puller
  daemonsetName: devworkspace-image-puller
  deploymentName: devworkspace-image-puller
  imagePullerImage: 'quay.io/eclipse/kubernetes-image-puller:next'
  images: {{ join ";" .Values.images }}