kind: ConfigMap
apiVersion: v1
metadata:
  name: auth-authelia
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}  
data:
  auth.yaml: |-
    authentication:
      clients:
        - clientId: rhtpa-front
          issuerUrl: "asdfasdf"
          #{{ .Values.oidc.issuer }}

          scopeSelector: "$['scp','groups']"

          scopeMappings:
            rhtpadr:
              - "ai"
              - "read.sbom"
              - "read.advisory"
              - "read.importer"
              - "read.metadata"
              - "read.sbomGroup"
              - "read.weakness"
              - "read.systemInformation"
            rhtpadw:
              - "create.sbom"
              - "create.advisory"
              - "create.importer"
              - "create.metadata"
              - "create.sbomGroup"
              - "create.weakness"
              - "update.sbom"
              - "update.advisory"
              - "update.importer"
              - "update.metadata"
              - "update.sbomGroup"
              - "update.weakness"
              - "upload.dataset"
            rhtpadu:
              - "update.sbom"
              - "update.advisory"
              - "update.importer"
              - "update.metadata"
              - "update.sbomGroup"
              - "update.weakness"
            rhtpadd:
              - "delete.sbom"
              - "delete.advisory"
              - "delete.importer"
              - "delete.metadata"
              - "delete.sbomGroup"
              - "delete.vulnerability"
              - "delete.weakness"

        - clientId: rhtpa-cli
          issuerUrl: {{ .Values.oidc.issuer }}
          requiredAudience: rhtpa-cli

          scopeSelector: "$['scp','groups']"

          scopeMappings:
            rhtpadr:
              - "ai"
              - "read.sbom"
              - "read.advisory"
              - "read.importer"
              - "read.metadata"
              - "read.sbomGroup"
              - "read.weakness"
              - "read.systemInformation"
            rhtpadw:
              - "create.sbom"
              - "create.advisory"
              - "create.importer"
              - "create.metadata"
              - "create.sbomGroup"
              - "create.weakness"
              - "update.sbom"
              - "update.advisory"
              - "update.importer"
              - "update.metadata"
              - "update.sbomGroup"
              - "update.weakness"
              - "upload.dataset"
            rhtpadu:
              - "update.sbom"
              - "update.advisory"
              - "update.importer"
              - "update.metadata"
              - "update.sbomGroup"
              - "update.weakness"
            rhtpadd:
              - "delete.sbom"
              - "delete.advisory"
              - "delete.importer"
              - "delete.metadata"
              - "delete.sbomGroup"
              - "delete.vulnerability"
              - "delete.weakness"