kind: Secret
apiVersion: v1
metadata:
  name: s3-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}  
stringData:
  user: {{ .Values.bucket.user }}
  password: {{ .Values.bucket.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}  
type: Opaque
stringData:
  db.host: {{ .Values.postgres.host }}
  db.name: {{ .Values.postgres.name }}
  db.user: {{ .Values.postgres.user }}
  db.password: {{ .Values.postgres.password }}
  db.port: {{ .Values.postgres.port }}
---
kind: Secret
apiVersion: v1
metadata:
  name: oidc-client-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}  
stringData:
  client-secret: {{ .Values.oidc.secret }}