apiVersion: batch/v1
kind: Job
metadata:
  name: remove-devspaces-operator-csv
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: delete-devspaces-operator
          image: quay.io/zcve/bashkc
          command:
            - bash
            - -c    
            - |
              kubectl delete --ignore-not-found=true subscription devworkspace-operator-fast-redhat-operators-openshift-marketplace -n openshift-operators
              kubectl delete --ignore-not-found=true csv `kubectl get csv --no-headers -o custom-columns=NAME:.metadata.name | grep -e devspacesoperator -e devworkspace-operator` -n openshift-operators
              kubectl delete --ignore-not-found=true deployment devworkspace-webhook-server -n openshift-operators
              kubectl delete --ignore-not-found=true service devworkspace-webhookserver -n openshift-operators
              