config:
  users:
  - name: redhat
    givenname: RedHat
    sn: RedHat
    mail: redhat@redhat.com
    uidnumber: 5001
    primarygroup: 5500
    otherGroups:
      - 5501
      - 6000
    passsha256: 7d3b5c83009fadf734c06eeecd7fbe256c69f71c8ba0429e4d7ad5f54b2e4097
    capabilities:
      - action: search
        object: "*"
    customattributes:
      - uid:
          - redhat
  - name: macastro
    givenname: Mauricio
    sn: Castro
    mail: macastro@redhat.com
    uidnumber: 5011
    primarygroup: 5500
    otherGroups:
      - 5501
      - 6000
      - 6001
      - 6002
      - 6003
    passsha256: 7d3b5c83009fadf734c06eeecd7fbe256c69f71c8ba0429e4d7ad5f54b2e4097
    capabilities:
      - action: search
        object: "*"
    customattributes:
      - uid:
          - macastro
  - name: admin
    givenname: Mauricio
    sn: Castro
    mail: admin@rhdh
    uidnumber: 5555
    primarygroup: 5555
    otherGroups:
      - 5500
      - 5501
      - 5502
      - 6000
      - 6001
      - 6002
      - 6003
    passsha256: 7d3b5c83009fadf734c06eeecd7fbe256c69f71c8ba0429e4d7ad5f54b2e4097
    capabilities:
      - action: search
        object: "*"
    customattributes:
      - uid:
          - admin
  - name: hi
    givenname: Hi
    sn: HowAreYou
    mail: hi@redhat.com
    uidnumber: 5003
    primarygroup: 5501
    passsha256: 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
    capabilities:
      - action: search
        object: "*"
    customattributes:
      - uid:
          - hi
  - name: dev1
    givenname: Mauricio
    sn: Castro
    mail: mauricioscastro@hotmail.com
    uidnumber: 5005
    primarygroup: 5502
    otherGroups:
      - 5501
      - 6000
    passsha256: 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
    capabilities:
      - action: search
        object: "*"
    customattributes:
      - uid:
          - dev1
  groups:
  - name: superheros
    gidnumber: 5501
  - name: dev
    gidnumber: 5502
  - name: admin
    gidnumber: 5555
  - name: rhtpadr
    gidnumber: 6000
  - name: rhtpadw
    gidnumber: 6001
  - name: rhtpadu
    gidnumber: 6002
  - name: rhtpadd
    gidnumber: 6003

  extra_users:
  - name: extra1
    givenname: extra
    sn: user
    mail: extra@example.com
    uidnumber: 5005
    primarygroup: 5502
    otherGroups:
      - 5501
      - 6000
    passsha256: 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
    capabilities:
      - action: search
        object: "*"
    customattributes:
      - uid:
          - extra1  
  
  extra_groups:
  - name: extra1
    gidnumber: 7000
  - name: extra2
    gidnumber: 7001

  
