kind: Secret
apiVersion: v1
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}  
stringData:
  minio_root_user: {{ .Values.user }}
  minio_root_password: {{ .Values.password }}

