apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: {{ .Release.Namespace }}
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard:
      logLevel: ERROR
    devWorkspace: {}
    devfileRegistry:
      disableInternalRegistry: true
    imagePuller: # created-separately
      enable: false
    metrics:
      enable: true
    pluginRegistry:
      externalPluginRegistries:
        - url: 'https://marketplace.visualstudio.com/'
      openVSXURL: 'https://open-vsx.org'
  containerRegistry: {}
  devEnvironments:
    startTimeoutSeconds: 300
    security: {}
    secondsOfRunBeforeIdling: 1800
    maxNumberOfWorkspacesPerUser: 5
    disableContainerRunCapabilities: false
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    disableContainerBuildCapabilities: false
    containerRunConfiguration:
      containerSecurityContext:
        allowPrivilegeEscalation: true
        capabilities:
          add:
            - SETGID
            - SETUID
            - CHOWN
        procMount: Unmasked
      openShiftSecurityContextConstraint: container-run
      workspacesPodAnnotations:
        io.kubernetes.cri-o.Devices: '/dev/fuse,/dev/net/tun'
    ignoredUnrecoverableEvents:
      - FailedScheduling
    maxNumberOfRunningWorkspacesPerUser: -1
    maxNumberOfRunningWorkspacesPerCluster: -1
    defaultNamespace:
      autoProvision: true
      template: <username>-devspaces
    secondsOfInactivityBeforeIdling: -1
    storage:
      pvcStrategy: per-workspace
    persistUserHome:
      enabled: true
  gitServices: {}
  networking:
    auth:
      gateway:
        configLabels:
          app: che
          component: che-gateway-config

