apiVersion: apps/v1
kind: Deployment
metadata:
  name: glauth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glauth
  template:
    metadata:
      labels:
        app: glauth
    spec:
      containers:
        - name: glauth
          image: docker.io/glauth/glauth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3389
            # - containerPort: 3636
          volumeMounts:
            - name: glauth-config-volume
              mountPath: /app/config
      volumes:
        - name: glauth-config-volume
          configMap:
            name: glauth